default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  pool: <%= ENV.fetch("POSTGRES_POOL") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  database: <%= ENV.fetch("POSTGRES_DBNAME") { 'cointrader_development' } %>
  <<: *default

test:
  database: cointrader_test
  <<: *default

production:
  database: <%= ENV.fetch("POSTGRES_DBNAME") { 'cointrader_production' } %>
  <<: *default
