# <Common>
variables:
  RAILS_ENV: 'test'
  SIMPLECOV: 'true'

  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: rails
  POSTGRES_PASSWORD: 'passw0rd'

  USE_BUNDLE_INSTALL: 'true'
  SETUP_DB: 'false'

  DEPLOY_USER: 'GitLab CD'
  DEPLOY_ICON: ':gitlab:'

.backend: &backend
  image: 'registry.gitlab.com/arb-club/arb/builder:ruby-2.5'
  before_script:
    - cd backend && gem update --system && gem install bundler --no-ri --no-rdoc
    - '[ "$USE_BUNDLE_INSTALL" != "true" ] || bundle install --path vendor --retry 3 --jobs 3'
    - '[ "$SETUP_DB" != "true" ] || bundle exec rails db:create db:schema:load db:migrate'

  cache:
    key: 'backend'
    paths:
      - backend/vendor

# </Common>

stages:
  - lint

# <Lint>
rubocop:
  <<: *backend
  stage: lint
  script:
    - bundle exec rubocop
