# Авторизация на сервисах
auth:
 

# Используемая стратегия
strategy:
  type: pair
  options: 
    market: WAVES-BTC
    exchanges: bittrex,binance
    minTradeSize: 0.1 # это минимально допустимый размер сделки (если на счету не осталось достаточно валюты, чтобы разместить по maxTradeSize) согласно тому, что продаем/покупаем
    minTradeRelative: 1 # это относительная доходность сделки
    maxTradeSize: 0.5 # тот объем, который максимально размещаем, чтобы да, не слить все )
    
